server:
  port: 8445
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ENC(idIWCdznEM3ggslDeTmLJw==)
    key-store-type: PKCS12
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  config:
    import: optional:file:.env[.properties]  # .env import
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ENC(idIWCdznEM3ggslDeTmLJw==)
  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
    openai:
#      api-key: ENC(JEvShe2gcGa5iJgLxKDlDR+0OjuSRIudWW16tT8IPHO4kdaYBBzBP49MhMJuq2G3)
#      chat:
#        options:
#          model: gemini-2.0-flash
#          temperature: 0.0
#          max-tokens: 1000
#          completions-path: /v1/chat/completions
#          base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      api-key: ENC(DIrd78xrB30lc2q7A5pW1OwT8+V5LbMcVryz5BbtbHMWa1zwwF6oDzxZGvWb/USsdjDccGQJV+Mx1IOfWiPO5rVG4TYWUuLDXM3U6h08yyAOAy3P2tas2v9yTLZvd9obwh3zcuT6gedYUhugwCdL/EoBq/Hsg01M9ENgrKPIfAeuFHOTu9eqEWMEAzNiPuD9l+4yU8WjNqff698QGXOfHd/nT6yKrVvgXtgaZtbBehs=)
      chat:
        options:
          model: gpt-4o
          temperature: 0.1
          max-tokens: 1000
mybatis:
  type-aliases-package: edu.sm.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info

# Application Config
# @Value("${}")
app:
  url:
    adminserver: https://192.168.1.6:8444/
  key:
    skey: ${MY_KEY}
#    chatgpt: ENC(DIrd78xrB30lc2q7A5pW1OwT8+V5LbMcVryz5BbtbHMWa1zwwF6oDzxZGvWb/USsdjDccGQJV+Mx1IOfWiPO5rVG4TYWUuLDXM3U6h08yyAOAy3P2tas2v9yTLZvd9obwh3zcuT6gedYUhugwCdL/EoBq/Hsg01M9ENgrKPIfAeuFHOTu9eqEWMEAzNiPuD9l+4yU8WjNqff698QGXOfHd/nT6yKrVvgXtgaZtbBehs=)
#     gemini: ENC(JEvShe2gcGa5iJgLxKDlDR+0OjuSRIudWW16tT8IPHO4kdaYBBzBP49MhMJuq2G3)

