server:
  port: 8445
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ENC(idIWCdznEM3ggslDeTmLJw==)
    key-store-type: PKCS12
spring:
  config:
    import: optional:file:.env[.properties]  # .env import
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ENC(idIWCdznEM3ggslDeTmLJw==)
  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
    openai:
      #      api-key: ENC(obMyxTHwYwf+dPSU0CceUz3IjH2DlRl/nrol+IV+g+D8Deau7yePKz18U+JYr4WQ)
      #      chat:
      #        options:
      #          model: gemini-2.0-flash-exp
      #          temperature: 0.0
      #          max-tokens: 1000
      #        completions-path: /v1/chat/completions
      #        base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      api-key: ENC(DIrd78xrB30lc2q7A5pW1OwT8+V5LbMcVryz5BbtbHMWa1zwwF6oDzxZGvWb/USsdjDccGQJV+Mx1IOfWiPO5rVG4TYWUuLDXM3U6h08yyAOAy3P2tas2v9yTLZvd9obwh3zcuT6gedYUhugwCdL/EoBq/Hsg01M9ENgrKPIfAeuFHOTu9eqEWMEAzNiPuD9l+4yU8WjNqff698QGXOfHd/nT6yKrVvgXtgaZtbBehs=)
      chat:
        options:
          model: gpt-4o
          temperature: 0.1
          max-tokens: 1000
mybatis:
  type-aliases-package: edu.sm.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info

# Application Config
# @Value("${}")
app:
  url:
    adminserver: https://192.168.1.3:8444/
  key:
    skey: ${MY_KEY}
#    chatgpt: ENC(O6nA7LHMxSeW3hk1fFx5ccHaycrF6yODAV6PmroPHVmgH4NUeNSO+Rq0gDAhwFsdHQVLv7rESR6i+Ki+j5tad6S/8DUypnK4LEO5gYShjIm4qMX4rGCLIECH3o2Z7qOY2Dlr+yaRlV5qBUVo/QnoUyURg2YwL7itFCpMi3Ue8CcKIdBrBxd4tiDXrzuxDEK2B1sThLv50kNedije/uBmUSo+kbdEJYEDMkfDQ/KSoGo=)
#    gemini: ENC(obMyxTHwYwf+dPSU0CceUz3IjH2DlRl/nrol+IV+g+D8Deau7yePKz18U+JYr4WQ)






